### ISSUE TITLE
Can this implement be applied to multi-output regression tasks?

### ISSUE THREAD

**Issue by wuyuhui-zju** [dholzmueller/bmdal_reg#1]
My dataset has multiple outputs, so can I use this implementation to compute k(grad) or k(ll)? Or are there frameworks for multi-output regression? thank you

**Comment by dholzmueller** [comment]
The code can directly be applied to a multi-output regression NN, it will treat the NN as if all outputs had been summed to a single output. The last-layer gradients will have the shape n_hidden x d_out even though all of the d_out columns will be identical. This redundancy is not exploited in the current implementation. This will not be very problematic for selection methods that use the kernel-based formulation such as MaxDet, MaxDist, KMeansPP, and LCMD, since the corresponding kernel computations scale like O(n_hidden + d_out). For methods that use the feature space formulation, such as BAIT and FrankWolfe, I would recommend to use random projections even for k(ll).

It might be possible to get better and theoretically nicer results for multi-output regression by using matrix-valued kernels based on Jacobians instead of gradients, but this would be a topic for another paper. For the last-layer kernel, I'm not sure if this would make a difference, but it should make a difference for the grad kernel.
